# Generated by Django 3.1.5 on 2021-02-02 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cat_level',
        ),
    ]
