# Generated by Django 3.1.5 on 2021-02-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dash_Cateogry',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=200)),
                ('category_level', models.IntegerField()),
                ('business_profile_id', models.IntegerField()),
            ],
            options={
                'db_table': 'dash_category',
            },
        ),
    ]
